apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cocodrilo
spec:
  maxReplicas: 10
  minReplicas: 2
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crocodile-api